image: tmaier/docker-compose:latest

services:
  - docker:dind

stages:
  - test
  - build

test:
  stage: test
  script:
    - docker-compose up --build -d
    - docker-compose exec api rake test
    - docker-compose down

build:
  stage: build
  script:
    - docker-compose up --build -d
    - docker commit $(docker ps -q) devscola/consensus1718:latest
    - docker login -u $HUB_DOCKER_USER -p $HUB_DOCKER_PSSW
    - docker push devscola/consensus1718
