image: tmaier/docker-compose:latest

services:
  - docker:dind

stages:
  - test

test:
  stage: test
  before_script:
    - docker-compose -f docker-compose.ci.yml up --build -d
  script:
    - docker-compose -f docker-compose.ci.yml run api bundle exec rake test
    - docker-compose -f docker-compose.ci.yml down
