stages:
  - build
  - test

test:
  stage: test
  image: ruby:2.4.2
  before_script:
    - bundle install
  script:
    - bundle exec rake &
    - bundle exec rake test

build:
  stage: build
  image: tmaier/docker-compose:latest
  services:
    - docker:dind
  script:
    - docker-compose up --build -d
    - docker commit $(docker ps -q) devscola/consensus1718:latest
    - echo $HUB_DOCKER_USER $HUB_DOCKER_PSSW | docker login --username --password-stdin
    - docker push devscola/consensus1718
    - docker logout
