stages:
  - test
  - build

build:
  image: ruby:2.4.2
  stage: test
  before_script:
    - bundle install
  script:
    - bundle exec rake &
    - bundle exec rake test

build:
  image: tmaier/docker-compose:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker-compose up --build -d
    - docker commit $(docker ps -q) devscola/consensus1718:latest
    - docker login -u $HUB_DOCKER_USER -p $HUB_DOCKER_PSSW
    - docker push devscola/consensus1718
