stages:
  - build
  - test

test:
  stage: test
  image: ruby:2.4.2
  before_script:
    - bundle install
  script:
    - bundle exec rake &
    - bundle exec rake test

build:
  stage: build
  image: tmaier/docker-compose:latest
  services:
    - docker:dind
  script:
    - docker login registry.gitlab.com
    - docker-compose up --build -d
    - docker commit $(docker ps -q) registry.gitlab.com/devscola/consensus-api
    - docker push registry.gitlab.com/devscola/consensus-api
    - docker logout
