version: '3.2'
services:
  api:
    build: .
    env_file:
      password_mail.env
    volumes:
      - type: bind
        source: .
        target: /opt/consensus_api/
    ports:
      - '4567:4567'
