version: '3.2'
services:
  api:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongo:27017/db
      - DOMAIN=localhost:8080
      - KEY='fake'
    links:
      - mongo

  mongo:
    image: mongo
    environment:
      - AUTH=no
    ports:
      - 27017:27017
